/**
 * Curated substitution catalog backed by USDA searches.
 * Focuses on common, taste-safe swaps grouped by functional roles.
 */

export const SUBSTITUTION_CATALOG = [
  // Lean proteins (omnivore)
  {
    id: 'chicken_breast',
    name: 'Chicken breast',
    roles: ['lean_protein', 'poultry'],
    diets: ['omnivore'],
    allergens: [],
    fdcQueries: ['chicken broiler breast meat raw', 'chicken breast raw'],
    tasteScore: 5,
    textureScore: 5,
    commonness: 5,
    gramRatio: 1,
    notes: 'Lean, neutral flavor; easy 1:1 swap for other poultry cuts.',
  },
  {
    id: 'turkey_breast',
    name: 'Turkey breast',
    roles: ['lean_protein', 'poultry'],
    diets: ['omnivore'],
    allergens: [],
    fdcQueries: ['turkey breast raw', 'turkey breast meat raw'],
    tasteScore: 4,
    textureScore: 4,
    commonness: 4,
    gramRatio: 1,
    notes: 'Mild flavor; slightly drier than chicken.',
  },
  {
    id: 'ground_turkey_93',
    name: '93% lean ground turkey',
    roles: ['lean_ground', 'lean_protein'],
    diets: ['omnivore'],
    allergens: [],
    fdcQueries: ['turkey ground raw 93% lean', 'ground turkey raw'],
    tasteScore: 4,
    textureScore: 4,
    commonness: 5,
    gramRatio: 1,
    notes: 'Neutral flavor; good swap for ground beef in most sautés.',
  },
  {
    id: 'lean_ground_beef_93',
    name: '93% lean ground beef',
    roles: ['lean_ground', 'red_meat'],
    diets: ['omnivore'],
    allergens: [],
    fdcQueries: ['beef ground 93% lean raw', 'ground beef 93% lean raw'],
    tasteScore: 5,
    textureScore: 5,
    commonness: 5,
    gramRatio: 1,
    notes: 'Keeps beef flavor with lower fat; works for burgers, sauces, tacos.',
  },
  {
    id: 'pork_tenderloin',
    name: 'Pork tenderloin',
    roles: ['lean_protein', 'pork'],
    diets: ['omnivore'],
    allergens: [],
    fdcQueries: ['pork tenderloin raw', 'pork loin tenderloin raw'],
    tasteScore: 4,
    textureScore: 4,
    commonness: 4,
    gramRatio: 1,
    notes: 'Mild flavor; leaner swap for fattier pork cuts.',
  },

  // Seafood
  {
    id: 'salmon_fillet',
    name: 'Salmon fillet',
    roles: ['seafood', 'fatty_fish', 'protein_plus_fat'],
    diets: ['pescatarian', 'omnivore'],
    allergens: ['fish'],
    fdcQueries: ['salmon atlantic raw', 'salmon fillet raw'],
    tasteScore: 5,
    textureScore: 5,
    commonness: 5,
    gramRatio: 1,
    notes: 'Rich flavor; adds healthy fats and protein.',
  },
  {
    id: 'white_fish_cod',
    name: 'Cod/tilapia (white fish)',
    roles: ['seafood', 'lean_protein'],
    diets: ['pescatarian', 'omnivore'],
    allergens: ['fish'],
    fdcQueries: ['cod atlantic raw', 'tilapia raw'],
    tasteScore: 4,
    textureScore: 4,
    commonness: 4,
    gramRatio: 1,
    notes: 'Mild flavor; good lean swap for other fish or poultry.',
  },
  {
    id: 'shrimp',
    name: 'Shrimp',
    roles: ['seafood', 'lean_protein'],
    diets: ['pescatarian', 'omnivore'],
    allergens: ['shellfish'],
    fdcQueries: ['shrimp raw', 'shrimp flesh raw'],
    tasteScore: 5,
    textureScore: 4,
    commonness: 4,
    gramRatio: 1,
    notes: 'Quick cooking, high protein; watch shellfish allergen.',
  },

  // Plant proteins
  {
    id: 'tofu_firm',
    name: 'Firm tofu',
    roles: ['plant_protein', 'lean_protein', 'binder'],
    diets: ['vegan', 'vegetarian'],
    allergens: ['soy'],
    fdcQueries: ['tofu firm raw', 'tofu raw'],
    tasteScore: 4,
    textureScore: 4,
    commonness: 4,
    gramRatio: 1,
    notes: 'Neutral flavor; absorbs marinades; great grilled/sauteed.',
  },
  {
    id: 'tempeh',
    name: 'Tempeh',
    roles: ['plant_protein'],
    diets: ['vegan', 'vegetarian'],
    allergens: ['soy'],
    fdcQueries: ['tempeh', 'soy tempeh'],
    tasteScore: 3,
    textureScore: 3,
    commonness: 3,
    gramRatio: 1,
    notes: 'Nutty flavor; best when marinated or crisped.',
  },
  {
    id: 'black_beans',
    name: 'Black beans',
    roles: ['plant_protein', 'legume', 'carb_plus_protein'],
    diets: ['vegan', 'vegetarian'],
    allergens: [],
    fdcQueries: ['beans black canned drained', 'black beans cooked'],
    tasteScore: 4,
    textureScore: 4,
    commonness: 5,
    gramRatio: 1,
    notes: 'Common swap for part of meat in tacos/chilis for fiber + protein.',
  },

  // Dairy + binders
  {
    id: 'greek_yogurt_nonfat',
    name: 'Nonfat Greek yogurt',
    roles: ['binder', 'creamy_dairy', 'protein_boost'],
    diets: ['vegetarian'],
    allergens: ['dairy'],
    fdcQueries: ['yogurt greek nonfat plain', 'greek yogurt plain nonfat'],
    tasteScore: 4,
    textureScore: 4,
    commonness: 5,
    gramRatio: 1,
    notes: 'Tangy; great mayo/sour cream sub; high protein.',
  },
  {
    id: 'cottage_cheese_lowfat',
    name: 'Low-fat cottage cheese',
    roles: ['creamy_dairy', 'protein_boost'],
    diets: ['vegetarian'],
    allergens: ['dairy'],
    fdcQueries: ['cottage cheese lowfat', 'cottage cheese 1%'],
    tasteScore: 3,
    textureScore: 3,
    commonness: 4,
    gramRatio: 1,
    notes: 'High protein; blend for smoothness.',
  },
  {
    id: 'part_skim_mozzarella',
    name: 'Part-skim mozzarella',
    roles: ['cheese'],
    diets: ['vegetarian'],
    allergens: ['dairy'],
    fdcQueries: ['cheese mozzarella part skim', 'mozzarella cheese part skim'],
    tasteScore: 4,
    textureScore: 4,
    commonness: 5,
    gramRatio: 1,
    notes: 'Melts well with lower fat than whole milk cheese.',
  },
  {
    id: 'parmesan',
    name: 'Parmesan (hard)',
    roles: ['cheese'],
    diets: ['vegetarian'],
    allergens: ['dairy'],
    fdcQueries: ['cheese parmesan hard', 'parmesan cheese'],
    tasteScore: 5,
    textureScore: 5,
    commonness: 5,
    gramRatio: 0.6,
    notes: 'Strong flavor; smaller amount achieves same salt/umami.',
  },
  {
    id: 'egg_white',
    name: 'Egg whites',
    roles: ['binder', 'lean_protein'],
    diets: ['vegetarian'],
    allergens: ['egg'],
    fdcQueries: ['egg white raw', 'egg whites raw'],
    tasteScore: 4,
    textureScore: 4,
    commonness: 5,
    gramRatio: 1,
    notes: 'Adds protein and binding with minimal fat.',
  },

  // Fats & oils
  {
    id: 'olive_oil',
    name: 'Olive oil',
    roles: ['fat_oil', 'finish_oil'],
    diets: ['vegan', 'vegetarian', 'pescatarian', 'omnivore'],
    allergens: [],
    fdcQueries: ['oil olive', 'olive oil'],
    tasteScore: 5,
    textureScore: 5,
    commonness: 5,
    gramRatio: 1,
    notes: 'Medium smoke point; great for sautés and finishing.',
  },
  {
    id: 'avocado_oil',
    name: 'Avocado oil',
    roles: ['fat_oil', 'high_heat_oil'],
    diets: ['vegan', 'vegetarian', 'pescatarian', 'omnivore'],
    allergens: [],
    fdcQueries: ['oil avocado', 'avocado oil'],
    tasteScore: 5,
    textureScore: 5,
    commonness: 4,
    gramRatio: 1,
    notes: 'Neutral flavor; high smoke point for searing/roasting.',
  },
  {
    id: 'canola_oil',
    name: 'Canola oil',
    roles: ['fat_oil', 'neutral_oil'],
    diets: ['vegan', 'vegetarian', 'pescatarian', 'omnivore'],
    allergens: [],
    fdcQueries: ['oil canola', 'canola oil'],
    tasteScore: 4,
    textureScore: 5,
    commonness: 5,
    gramRatio: 1,
    notes: 'Neutral flavor; good budget swap for high-heat cooking.',
  },
  {
    id: 'ghee',
    name: 'Ghee',
    roles: ['fat_oil', 'high_heat_oil', 'butter_alternative'],
    diets: ['vegetarian', 'pescatarian', 'omnivore'],
    allergens: ['dairy'],
    fdcQueries: ['ghee', 'butter oil anhydrous'],
    tasteScore: 5,
    textureScore: 5,
    commonness: 4,
    gramRatio: 1,
    notes: 'Butter flavor with higher smoke point; lactose removed but still dairy.',
  },

  // Carbs & bases
  {
    id: 'white_rice',
    name: 'White rice',
    roles: ['carb_base'],
    diets: ['vegan', 'vegetarian', 'pescatarian', 'omnivore'],
    allergens: [],
    fdcQueries: ['rice white long grain raw', 'rice white cooked'],
    tasteScore: 5,
    textureScore: 5,
    commonness: 5,
    gramRatio: 1,
    notes: 'Neutral base; default for many dishes.',
  },
  {
    id: 'brown_rice',
    name: 'Brown rice',
    roles: ['carb_base', 'higher_fiber_carb'],
    diets: ['vegan', 'vegetarian', 'pescatarian', 'omnivore'],
    allergens: [],
    fdcQueries: ['rice brown long grain raw', 'brown rice cooked'],
    tasteScore: 4,
    textureScore: 4,
    commonness: 5,
    gramRatio: 1,
    notes: 'More fiber and slightly chewier than white rice.',
  },
  {
    id: 'quinoa',
    name: 'Quinoa',
    roles: ['carb_base', 'carb_plus_protein'],
    diets: ['vegan', 'vegetarian', 'pescatarian', 'omnivore'],
    allergens: [],
    fdcQueries: ['quinoa uncooked', 'quinoa cooked'],
    tasteScore: 4,
    textureScore: 4,
    commonness: 4,
    gramRatio: 1,
    notes: 'Adds protein and fiber; nutty flavor.',
  },
  {
    id: 'cauliflower_rice',
    name: 'Cauliflower rice',
    roles: ['low_carb_base'],
    diets: ['vegan', 'vegetarian', 'pescatarian', 'omnivore'],
    allergens: [],
    fdcQueries: ['cauliflower raw', 'cauliflower cooked'],
    tasteScore: 3,
    textureScore: 3,
    commonness: 4,
    gramRatio: 1,
    notes: 'Low-calorie base; best when sautéed to remove moisture.',
  },
  {
    id: 'whole_wheat_pasta',
    name: 'Whole-wheat pasta',
    roles: ['carb_base', 'higher_fiber_carb'],
    diets: ['vegan', 'vegetarian', 'pescatarian', 'omnivore'],
    allergens: ['gluten'],
    fdcQueries: ['pasta whole wheat dry', 'spaghetti whole wheat dry'],
    tasteScore: 4,
    textureScore: 4,
    commonness: 4,
    gramRatio: 1,
    notes: 'More fiber than white pasta; slightly nuttier flavor.',
  },
  {
    id: 'chickpea_pasta',
    name: 'Chickpea pasta',
    roles: ['carb_plus_protein', 'higher_fiber_carb'],
    diets: ['vegan', 'vegetarian', 'pescatarian', 'omnivore'],
    allergens: ['legume'],
    fdcQueries: ['pasta chickpea dry', 'chickpea pasta'],
    tasteScore: 3,
    textureScore: 3,
    commonness: 3,
    gramRatio: 1,
    notes: 'Higher protein/fiber; slightly firmer texture.',
  },
  {
    id: 'zucchini_noodles',
    name: 'Zucchini noodles',
    roles: ['low_carb_base'],
    diets: ['vegan', 'vegetarian', 'pescatarian', 'omnivore'],
    allergens: [],
    fdcQueries: ['squash zucchini raw', 'zucchini raw'],
    tasteScore: 3,
    textureScore: 3,
    commonness: 3,
    gramRatio: 1,
    notes: 'Very low calorie; quick sauté avoids sogginess.',
  },
  {
    id: 'corn_tortilla',
    name: 'Corn tortilla',
    roles: ['bread_wrap'],
    diets: ['vegan', 'vegetarian', 'pescatarian', 'omnivore'],
    allergens: [],
    fdcQueries: ['tortilla corn', 'corn tortilla'],
    tasteScore: 5,
    textureScore: 5,
    commonness: 5,
    gramRatio: 1,
    notes: 'Common swap for flour tortilla; lower calorie, gluten-free.',
  },
  {
    id: 'whole_wheat_tortilla',
    name: 'Whole-wheat tortilla',
    roles: ['bread_wrap', 'higher_fiber_carb'],
    diets: ['vegan', 'vegetarian', 'pescatarian', 'omnivore'],
    allergens: ['gluten'],
    fdcQueries: ['tortilla whole wheat', 'whole wheat tortilla'],
    tasteScore: 4,
    textureScore: 4,
    commonness: 4,
    gramRatio: 1,
    notes: 'More fiber than flour tortillas; similar handling.',
  },
  {
    id: 'rolled_oats',
    name: 'Rolled oats',
    roles: ['carb_base', 'binder'],
    diets: ['vegan', 'vegetarian', 'pescatarian', 'omnivore'],
    allergens: ['gluten_optional'],
    fdcQueries: ['oats regular', 'rolled oats'],
    tasteScore: 4,
    textureScore: 4,
    commonness: 5,
    gramRatio: 1,
    notes: 'Good binder for meatballs/loaves; adds fiber.',
  },
];

export function getCandidatesForRoles(roles = []) {
  if (!roles || !roles.length) return [];
  const roleSet = new Set(roles);
  return SUBSTITUTION_CATALOG.filter((item) =>
    item.roles.some((role) => roleSet.has(role))
  );
}

export function getCatalogCandidate(id) {
  return SUBSTITUTION_CATALOG.find((item) => item.id === id) || null;
}
